item {
 id: 1
 name: '石头'
}
item {
 id: 2
 name: '食指'
}
item {
 id: 3
 name: '小指'
}
item {
 id: 4
 name: '枪'
}
item {
 id: 5
 name: '剪刀'
}
item {
 id: 6
 name: '三分'
}
item {
 id: 7
 name: '六六六'
}
item {
 id: 8
 name: '我爱你'
}
item {
 id: 9
 name: '布'
}
item {
 id: 10
 name: '观音'
}
